sansis_core_base_homepage:
    pattern:  /
    defaults: { _controller: SanSISCoreBaseBundle:Default:index }

sansis_core_base_logout:
    pattern:  /logout
    defaults: { _controller: SanSISCoreBaseBundle:Default:logout }

    
    