parameters:
  Ibram_core_base.service_data_class: Ibram\Core\BaseBundle\ServiceLayer\ServiceData

services:
  Ibram_core_base.service_data_injector:
    class: %Ibram_core_base.service_data_class%
    public: true
    arguments: ['@service_container']