parameters:
#    san_sis_core_base.example.class: SanSIS\Core\BaseBundle\Example

services:
#    san_sis_core_base.example:
#        class: %san_sis_core_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
